blueprints/task.py
import os
from asyncio import tasks
from alembic.script.write_hooks import console_scripts
from flask import Blueprint, session, request, redirect, url_for, flash
from flask import render_template
from form import form
from werkzeug.utils import secure_filename
from common.image import Image
from blueprints import user
from exts import db
from forms import TaskForm, TitleForm

from models import UserModel, TaskModel, TitleModel

bp = Blueprint('task', __name__, url_prefix="/task")

#set upload image file and file extension name
UPLOAD_FOLDER = 'static/media/'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

#dashboard page
@bp.route('/dashboard',methods=['GET', 'POST'])
def dashboard():
    if request.method == 'GET':
        user_id = session.get('user_id')
        titles_data = TitleModel.query.filter_by(user_id=user_id).all()
        return render_template('dashboard.html',titles_data=titles_data)
    else:
        form = TitleForm(request.form)
        if form.validate():
            titleName = form.titleName.data
            reviewNote = "None"
            user_id = session.get('user_id')
            newTitle = TitleModel(titleName=titleName, reviewNote=reviewNote, user_id=user_id)

            # print(newTitle.titleName)
            # print(newTitle.reviewNote)
            # print(newTitle.user_id)

            db.session.add(newTitle)
            db.session.commit()
            title_id = newTitle.id                                               # can be removed????
            flash("New task list created successfully")
            return redirect(url_for("task.dashboard",title_id=title_id)) #title_id = title_id canbe removed?
        else:
            flash("Cannot find user")
            print(form.errors)
            return redirect(url_for("task.dashboard"))

# write review note
@bp.route('/review/<int:title_id>',methods=['GET', 'POST'])
def review(title_id):
    # print(title_id)
    review_title = TitleModel.query.get_or_404(title_id)
    form = TitleForm(request.form)
    if request.method == 'POST':

        if form.validate():

            review_title.reviewNote = request.form.get('reviewNote',"").strip()
            review_title.user_id = session.get('user_id')

            db.session.commit()
            flash("Note added successfully")
            return redirect(url_for("task.dashboard",title_id=title_id))
        else:
            flash("Note added unsuccessfully")
            return redirect(url_for("task.review",title_id=title_id))

    else:
            # print(review_title)
            return render_template('review.html', title=review_title,form=form)

# delete function for all tasks under same title
@bp.route('/delete/<int:title_id>',methods=['POST'])
def delete(title_id):
    delete_title = TitleModel.query.get_or_404(title_id)

    TaskModel.query.filter_by(title_id=title_id).delete()
    db.session.delete(delete_title)
    db.session.commit()
    flash("Task deleted successfully")

    return redirect(url_for("task.dashboard"))

#adding tasks page
@bp.route('/home/<int:title_id>',methods=['GET', 'POST'])
def home(title_id):
    if request.method == 'POST':

            description = request.form['description']
            status = request.form.get('task-status')
            priority = request.form.get('task-priorities')
            image = ""

            #Adding new task
            new_task = TaskModel(description=description, status=status, priority=priority, title_id=title_id,image=image)

            db.session.add(new_task)
            db.session.commit()

            flash("Task add successfully")
            return redirect(url_for("task.home",title_id=title_id))
    else:
        #display all tasks from same title
        tasks_data = TaskModel.query.filter_by(title_id=title_id).all()
        return render_template('home.html',tasks_data=tasks_data,title_id=title_id)


# delete tasks
@bp.route('/deleteTask/<int:task_id>',methods=['POST'])
def deleteTask(task_id):

    delete_task = TaskModel.query.get_or_404(task_id)

    title_id = delete_task.title_id

    #delete image
    if delete_task.image:
        file_path = os.path.join('static/media', delete_task.image)
        if os.path.exists(file_path):
            os.remove(file_path)

    # print(f"Delete Task {task_id}")

    db.session.delete(delete_task)
    db.session.commit()
    flash("Task deleted successfully")

    return redirect(url_for("task.home",title_id = title_id))

@bp.route('/editTask/<int:task_id>',methods=['GET', 'POST'])
def editTask(task_id):
    # edit_task = TaskModel.query.get_or_404(task_id)
    edit_task = db.session.execute(db.select(TaskModel).filter_by(id = task_id)).scalar_one()

    if request.method == 'POST':

        edit_task.description = request.form.get('description')
        edit_task.status = request.form.get('task-status')
        edit_task.priority = request.form.get('task-priorities')

        # print(request.form)

        db.session.commit()
        flash("Task edited successfully")
        return redirect(url_for("task.home",title_id = edit_task.title_id))
    else:
        return render_template('editTask.html',task=edit_task)

# upload images
@bp.route('/upload/<int:task_id>',methods=['GET','POST'])
def upload(task_id):

    uploadImage_task = db.session.execute(db.select(TaskModel).filter_by(id=task_id)).scalar_one()

    if request.method == 'POST':

        file = request.files['image']

        if 'image' not in request.files:
            flash("No file provided")
            return redirect(url_for("task.home",title_id = uploadImage_task.title_id))

        if file.filename == '':
            flash("No file selected for uploading")
            return redirect(url_for("task.home",title_id = uploadImage_task.title_id))

        if file and allowed_file(file.filename):

            file_path = Image.get_images_path()
            filename = secure_filename(file.filename)
            fullpath = file_path.joinpath(filename)
            file.save(fullpath)

            #print(filename)

            uploadImage_task.image=filename

            db.session.commit()

            flash("Uploaded successfully")
            return redirect(url_for("task.home",title_id = uploadImage_task.title_id))

        else:
            flash("File type not supported.")
            return redirect(url_for("task.home",title_id = uploadImage_task.title_id))

    else:
        return redirect(url_for("task.home",title_id = uploadImage_task.title_id))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{% endblock %}</title>
    <link href ="{{ url_for ('static',filename='css/stylesheet.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
    integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<!--    <script src="{{url_for('static',filename='js/main.js')}}"></script>-->
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}


{% block title %}Dashboard{% endblock %}

{% block content %}

  <div class="header">
    <ul class="tab-nav">
      <li>
        <a href="{{ url_for ('task.dashboard') }}"  title="dashboard">Dashboard</a>
      </li>
      <li>
        <a href= "/user/update">{{user.firstName}}</a>
      </li>
      <li>
        <a href="{{ url_for ('index') }}" title="landing page">Logout</a>
      </li>
    </ul>
  </div>
      {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
        <span class = "flash-text">{{ message }}</span>
      {% endfor %}
    {% endif %}
  {% endwith %}
  <div class="home">
    <div class="container">
      <div class="todo">
        <h1>Dashboard</h1>
        <div class="user-details">
          <div data-prop="titleName" class="from-item">
              <form class="input-box" method="POST">
                <input type="text" id="titleName" name="titleName" placeholder="Add task title to start">
                <button type="submit">Create</button>
              </form>
          </div>
        </div>
      {% for title in titles_data %}
        <div class="todo-container">
          <ul id="task-list">
            <li>
              <h3>{{title.titleName}}</h3>
            </li>
            <li>
              <p id="review">{{title.reviewNote}}</p>
            </li>
            <li>
              <div class="btn-container">
                <a class="btn" href="{{ url_for('task.review', title_id=title.id) }}"><i class="fa-solid fa-comment"></i></a>
                <a class="btn" href="{{ url_for('task.home', title_id=title.id) }}"><i class="fa-solid fa-pen"></i></a>
                <form action="{{ url_for('task.delete',title_id = title.id)}}" method="POST">
                  <button class="btn" type = "submit"><i class="fa-solid fa-trash"></i></button>
                </form>
              </div>
            </li>
          </ul>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}
<script>
  function reviewFunction() {
    let text;
    let review = prompt("Please write reflective notes about tasks.");
    if (review == null || review == "") {
      text = "write remarks or reflective notes";
    } else {
      text = review;
    }
    document.getElementById("review").innerHTML = text;
  }
</script>

templates/editTask.html
{% extends "base.html" %}

{% block title %}Edit Task{% endblock %}

{% block content %}
  <div class="header">
    <ul class="tab-nav">
      <li>
        <a href="{{ url_for ('task.dashboard') }}" title="dashboard">Dashboard</a>
      </li>
      <li>
        <a href="{{ url_for ('user.update') }}">{{ user.firstName }}</a>
      </li>
      <li>
        <a href="{{ url_for ('index') }}" title="landing page">Logout</a>
      </li>
    </ul>
  </div>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <span class = "flash-text">{{ message }}</span>
          {% endfor %}
        {% endif %}
      {% endwith %}
  <div class="home">
    <div class="container">
      <div class="todo">
        <h1>Edit Task</h1>
        <div class="user-details">
          <form class="input-box" action="{{ url_for('task.editTask',task_id=task.id) }}" method="POST">

            <select id="task-status" name="task-status" class="task-status">
              <option value="Yet-to-Do" {% if task.status == "Yet-to-Do" %} selected {% endif %}>Yet-to-Do</option>
              <option value="On-Going" {% if task.status == "On-Going" %} selected {% endif %}>On-Going</option>
              <option value="Completed" {% if task.status == "Completed" %} selected {% endif %}>Completed</option>
            </select>

            <select id="task-priorities" name="task-priorities" class="task-priorities">
              <option value="Low" {% if task.priority == "Low"%} selected {% endif %}>Low</option>
              <option value="Medium" {% if task.priority == "Medium"%} selected {% endif %}>Medium</option>
              <option value="High" {% if task.priority == "High"%} selected {% endif %}>High</option>
            </select>

            <input type="text" id="description" name="description" value="{{task.description}}">
            <button class="btn" type="submit" id="add-task-btn"><i class="fa-solid fa-plus"></i></button>

          </form>
        </div>
        <div class="edit-btns">
            <a class="btn" href="{{url_for('task.home',title_id=task.title_id)}}"><i class="fa-solid fa-arrow-left"></i></a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="header">
    <ul class="tab-nav">
      <li>
        <a href="{{ url_for ('task.dashboard') }}" title="dashboard">Dashboard</a>
      </li>
      <li>
        <a href="{{ url_for ('user.update') }}">{{ user.firstName }}</a>
      </li>
      <li>
        <a href="{{ url_for ('index') }}" title="landing page">Logout</a>
      </li>
    </ul>
  </div>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <span class = "flash-text">{{ message }}</span>
          {% endfor %}
        {% endif %}
      {% endwith %}
  <div class="home">
    <div class="container">
      <div class="todo">
        <h1>To Do List</h1>
        <div class="user-details">
          <form class="input-box" action="{{ url_for('task.home',title_id=title_id) }}" method="POST">
            <select id="task-status" name="task-status" class="task-status">
              <option value="Yet-to-Do" selected>Yet-to-Do</option>
              <option value="On-Going">On-Going</option>
              <option value="Completed">Completed</option>
            </select>
            <select id="task-priorities" name="task-priorities" class="task-priorities">
              <option value="Low" selected>Low</option>
              <option value="Medium">Medium</option>
              <option value="High">High</option>
            </select>
            <input type="text" id="description" name="description" placeholder="Add a new task">
            <button type="submit" id="add-task-btn"><i class="fa-solid fa-plus"></i></button>
          </form>

        </div>
        {% for task in tasks_data %}
        <div class="todo-container">
          <div class="todo-list">
            <ul id="task-list">
              <li>Status: {{task.status}}</li>
              <li>Priority: {{task.priority}}</li>
              <li>{{task.description}}</li>
              {% if task.image %}
              <li>
                <image src = "{{url_for ('static', filename = 'media/' + task.image) }}"
                       alt = "Task Image" height="200" width = "200" onerror ="this.onerror = null;
                       this.style.display = 'none'"></image>
              </li>
              {% endif %}
              <li>
                <div class="task-btns">
                  <div class="btn-container">
                    <form action="{{ url_for ('task.editTask',task_id = task.id) }}" method="POST">
                      <a class="btn" href="{{ url_for('task.editTask', task_id = task.id) }}"><i class="fa-solid fa-pen"></i></a>
                    </form>
                    <form action="{{ url_for('task.upload', task_id=task.id) }}" method="POST" enctype="multipart/form-data" style="display:inline-block;">
                      <label class="btn" for="file-{{ task.id }}"> <i class="fa-solid fa-image"></i></label>
                      <input id="file-{{ task.id }}" type="file" name="image" accept="image/*" style="display:none;" onchange="this.form.submit();">
                  </form>
                    <form action="{{ url_for ('task.deleteTask',task_id = task.id) }}" method="POST">
                      <button class="btn" type="submit"><i class="fa-solid fa-trash"></i></button>
                    </form>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}

<script>

document.addEventListener('DOMContentLoaded', () => {
  const taskInput = document.getElementById('task-input');
  const addTaskBtn = document.getElementById('add-task-btn');
  const taskList = document.getElementById('task-list');


  const addTask = (event) => {
    event.preventDefault();
    const taskText = taskInput.value.trim();
    if (!taskText) {
      return;
    }
    //edit button
    const editBtn = li.querySelector('.edit-btn');
    editBtn.addEventListener('click', () => {
      taskInput.value = li.querySelector('span').textContent;
      li.remove();
    });

    //li.textContent = taskText;
    taskList.appendChild(li);
    taskInput.value = '';
  };

  addTaskBtn.addEventListener('click', addTask);
  taskInput.addEventListener('keypress', (e) => {

    if (e.key === 'Enter') {
      addTask(e)
    }

  })
})
</script>

templates/index.html
{%extends 'base.html'%}


{% block title %}Login{% endblock %}

{% block content %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
        <p class = "flash-text">{{ message }}</p>
      {% endfor %}
    {% endif %}
  {% endwith %}
  <div class="landing">

    <div class="container">
      <div class="title">Online Task Management</div>
      <form class="login" autocomplete="off" method="post">
        <div class="user-details">
          <div class="input-box">
            <span class="details">Email</span>
            <input type="text" placeholder="Enter Email" name="email" id="email" required>
          </div>

          <div class="input-box">
            <span class="details">Password</span>
            <input type="password" placeholder="Enter Password" name="password" id="password" required>
          </div>

          <div class="link">
            <div class="checkbox-content">
              <input type="checkbox" id="remember">
              <label for="remember" class="text">Remember me</label>
            </div>
            <button class="login">Submit</button>

            <div class="register">
              <a href="#" class="text" >Forgot password?</a>
              <a href="{{ url_for ('user.registration') }}" title="registration page">Register as new user</a>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/registration.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
        <p class = "flash-text">{{ message }}</p>
      {% endfor %}
    {% endif %}
  {% endwith %}
  <div class="registrationPage">
    <div class="container">
      <div class="title">Registration</div>
      <form class="registration" method="post">
        <div class="user-details">
          <div class="input-box">
            <div data-prop="firstName" class="from-item">
              <span class="details">First Name:</span>
              <input type="text" placeholder="Your First Name" name="firstName" required>
            </div>
          </div>

          <div class="input-box">
            <div data-prop="lastName" class="from-item">
              <span class="details">Last Name:</span>
              <input type="text" placeholder="Your Last Name" name="lastName" required>
            </div>
          </div>

          <div class="input-box">
            <div data-prop="email" class="from-item">
              <span class="details">Email Address:</span>
              <input type="text" placeholder="Your Email Address" name="email" required>
            </div>
          </div>

          <div class="input-box">
            <div data-prop="phone" class="from-item">
              <span class="details">Phone Number:</span>
              <input type="phone" placeholder="Your Phone number" name="phone" required>
            </div>
          </div>

          <div class="input-box">
            <div data-prop="password" class="from-item">
              <span class="details">Password:</span>
              <input type="password" placeholder="Enter You Password" name="password" id="password" required>
            </div>
          </div>

          <div class="input-box">
            <div data-prop="confirm" class="from-item">
              <span class="details">Confirm Password:</span>
              <input type="password" placeholder="Confirm Your Password" name="confirm" id="confirm" required>
            </div>
          </div>

          <div class="from-item">
            <button class="submit">Submit</button>
            <button type="button" onclick="location.href='{{ url_for ('index') }}'" class="cancel">Cancel</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/review.html
{% extends 'base.html' %}


{% block title %}Task Review{% endblock %}

{% block content %}

  <div class="header">
    <ul class="tab-nav">
      <li>
        <a href="{{ url_for ('task.dashboard') }}"  title="dashboard">Dashboard</a>
      </li>
      <li>
        <a href= "/user/update">ID: {{user.id}} -- Name: {{user.firstName}}</a>
      </li>
      <li>
        <a href="{{ url_for ('index') }}" title="landing page">Logout</a>
      </li>
    </ul>
  </div>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <span class = "flash-text">{{ message }}</span>
          {% endfor %}
        {% endif %}
      {% endwith %}
  <div class="home">
    <div class="container">
      <div class="todo">
        <h1>Task Review</h1>
        <form class="input-box" action="/task/review/{{title.id}}" method="POST">
          <h3>Task: {{title.titleName}}</h3>
          <div class="user-details">
            <div data-prop="reviewNote" class="from-item">
                <input type="text" name="reviewNote" value="{{title.reviewNote}}">
                <button type="submit">Add</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/update.html
{% extends "base.html" %}

{% block title %}Update{% endblock %}


{% block content %}
  <div class="header">
    <ul class="tab-nav">
      <li>
        <a href="{{ url_for ('task.dashboard') }}" title="dashboard">Dashboard</a>
      </li>
      <li>
        <a href="{{ url_for ('user.update') }}">{{ user.firstName }}</a>
      </li>
      <li>
        <a href="{{ url_for ('index') }}" title="landing page">Logout</a>
      </li>

    </ul>
  </div>
  <div class="registrationPage">
    <div class="container">
      <div class="title">Details Update</div>
      <form class="registration" method="post" action = "/user/update">
        <div class="user-details">

          <div class="input-box">
            <div data-prop="firstName" class="from-item">
              <span class="details">First Name:</span>
              <input type="text" value="{{user.firstName}}" name="firstName" required>
            </div>
          </div>

          <div class="input-box">
            <div data-prop="lastName" class="from-item">
              <span class="details">Last Name:</span>
              <input type="text" value="{{user.lastName}}" name="lastName" required>
            </div>
          </div>

          <div class="input-box">
            <div data-prop="email" class="from-item">
              <span class="details">Email Address:</span>
              <input type="text" value="{{user.email}}" name="email" required>
            </div>
          </div>

          <div class="input-box">
            <div data-prop="phone" class="from-item">
              <span class="details">Phone Number:</span>
              <input type="phone" value="{{user.phone}}" name="phone" required>
            </div>
          </div>

          <div class="input-box">
            <div data-prop="password" class="from-item">
              <span class="details">Password:</span>
              <input required type="password" placeholder="Enter You Password" name="password" id="password">
            </div>
          </div>

          <div class="input-box">
            <div data-prop="confirm" class="from-item">
              <span class="details">Confirm Password:</span>
              <input required type="password" placeholder="Confirm Your Password"  name="confirm" id="confirm">
            </div>
          </div>

          <div class="from-item">
            <button class="submit">Submit</button>
            <button class="cancel">Cancel</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}